import type { DemoLibrary } from './types';

export const DEMO_LIBRARIES: DemoLibrary[] = [
  // ── Calisthenics (mixed categories for visual variety) ──
  {
    id: 'calisthenics',
    name: 'Calisthenics',
    image: '/images/goals/muscle-up.webp',
    defaultGoalSlug: 'muscle-up',
    categories: [
      { id: 'push', name: 'Push', color: '#ef4444' },
      { id: 'pull', name: 'Pull', color: '#3b82f6' },
      { id: 'core', name: 'Core', color: '#f59e0b' },
    ],
    skills: [
      {
        id: 'push-up',
        name: 'Push-up',
        categoryId: 'push',
        requires: [],
        progressions: 3,
        description: 'The foundational pushing movement. Full range from chest to floor to lockout.',
        progressionPreview: 'Knee Push-up',

      },
      {
        id: 'dip',
        name: 'Dip',
        categoryId: 'push',
        requires: ['push-up'],
        progressions: 3,
        description: 'Vertical push on parallel bars. Builds chest, shoulders, and triceps strength.',
        progressionPreview: 'Bench Dip',

      },
      {
        id: 'pull-up',
        name: 'Pull-up',
        categoryId: 'pull',
        requires: ['dip'],
        progressions: 3,
        description: 'Pull chin over bar with full range of motion. The foundational upper-body pull.',
        progressionPreview: 'Negative Pull-up',
      },
      {
        id: 'bar-mu',
        name: 'Bar Muscle-up',
        abbr: 'Muscle-up',
        categoryId: 'pull',
        requires: ['pull-up'],
        progressions: 3,
        description: 'Explosive pull transitioning over the bar into a dip. 5 consecutive strict reps to master.',
        progressionPreview: 'Jumping Muscle-up',
      },
      {
        id: 'l-sit',
        name: 'L-sit',
        categoryId: 'core',
        requires: ['pull-up'],
        progressions: 3,
        description: 'Hold body off ground with legs extended horizontally. Pure core and shoulder compression.',
        progressionPreview: 'Tucked L-sit',
      },
    ],
    progress: {
      'push-up': { status: 'mastered', currentStep: 3 },
      dip: { status: 'completed', currentStep: 3 },
      'pull-up': { status: 'completed', currentStep: 3 },
      'bar-mu': { status: 'in_progress', currentStep: 1 },
      'l-sit': { status: 'in_progress', currentStep: 1 },
    },
  },

  // ── Mobility ──
  {
    id: 'mobility',
    name: 'Mobility',
    image: '/images/goals/front-split.webp',
    defaultGoalSlug: 'front-split',
    categories: [{ id: 'flexibility', name: 'Flexibility', color: '#14b8a6' }],
    skills: [
      {
        id: 'cat-cow',
        name: 'Cat-Cow',
        categoryId: 'flexibility',
        requires: [],
        progressions: 2,
        description: 'Alternating spinal flexion and extension on all fours. Warms up the entire spine segmentally.',
        progressionPreview: 'Gentle Cat-Cow',
      },
      {
        id: 'thoracic-rotation',
        name: 'Thoracic Rotation',
        categoryId: 'flexibility',
        requires: ['cat-cow'],
        progressions: 2,
        description: 'Side-lying thoracic spine rotation. Opens the upper back and improves rotational capacity.',
        progressionPreview: 'Supported Rotation',
      },
      {
        id: 'jefferson-curl',
        name: 'Jefferson Curl',
        categoryId: 'flexibility',
        requires: ['cat-cow'],
        progressions: 2,
        description: 'Standing segmental spinal flexion with light load. Targets hamstrings and posterior chain.',
        progressionPreview: 'Bodyweight Jefferson Curl',
      },
      {
        id: 'deep-squat-hold',
        name: 'Deep Squat Hold',
        categoryId: 'flexibility',
        requires: [],
        progressions: 2,
        description: 'Resting deep squat targeting hip flexion, ankle dorsiflexion, and thoracic extension.',
        progressionPreview: 'Assisted Deep Squat',
      },
      {
        id: 'hip-cars',
        name: 'Hip CARs',
        categoryId: 'flexibility',
        requires: ['deep-squat-hold'],
        progressions: 2,
        description: 'Controlled Articular Rotations for the hip. Slow circles through full available range.',
        progressionPreview: 'Supported Hip CARs',
      },
      {
        id: '90-90-stretch',
        name: '90/90 Stretch',
        categoryId: 'flexibility',
        requires: ['hip-cars'],
        progressions: 2,
        description: 'Both legs at 90° angles targeting hip internal and external rotation simultaneously.',
        progressionPreview: 'Supported 90/90',
      },
    ],
    progress: {
      'cat-cow': { status: 'mastered', currentStep: 2 },
      'thoracic-rotation': { status: 'completed', currentStep: 2 },
      'jefferson-curl': { status: 'in_progress', currentStep: 1 },
      'deep-squat-hold': { status: 'completed', currentStep: 2 },
      'hip-cars': { status: 'in_progress', currentStep: 1 },
      '90-90-stretch': { status: 'locked', currentStep: 0 },
    },
  },

  // ── Acrobatics / Tumbling ──
  {
    id: 'acrobatics',
    name: 'Acrobatics',
    image: '/images/goals/aerial-cartwheel.webp',
    defaultGoalSlug: 'aerial-cartwheel',
    categories: [{ id: 'tumbling', name: 'Tumbling', color: '#ec4899' }],
    skills: [
      {
        id: 'tmb-forward-roll',
        name: 'Forward Roll',
        categoryId: 'tumbling',
        requires: [],
        progressions: 2,
        description: 'Tuck the chin, push off the feet, and roll forward along the spine to standing.',
        progressionPreview: 'Downhill Forward Roll',
      },
      {
        id: 'tmb-cartwheel',
        name: 'Cartwheel',
        categoryId: 'tumbling',
        requires: ['tmb-forward-roll'],
        progressions: 2,
        description: 'Lateral rotation through hand-hand-foot-foot pattern with straight legs.',
        progressionPreview: 'Partial Cartwheel',
      },
      {
        id: 'tmb-aerial',
        name: 'Aerial Cartwheel',
        abbr: 'Aerial',
        categoryId: 'tumbling',
        requires: ['tmb-cartwheel'],
        progressions: 3,
        description: 'No-hands cartwheel — a true aerial rotation. The iconic tumbling milestone.',
        progressionPreview: 'Dive Aerial (low)',
      },
      {
        id: 'tmb-headstand',
        name: 'Headstand',
        categoryId: 'tumbling',
        requires: ['tmb-forward-roll'],
        progressions: 2,
        description: 'Tripod inversion with head and both hands forming triangle base. Foundation for handstands.',
        progressionPreview: 'Tripod Headstand (tuck)',
      },
      {
        id: 'tmb-bridge',
        name: 'Bridge Hold',
        abbr: 'Bridge',
        categoryId: 'tumbling',
        requires: ['tmb-headstand'],
        progressions: 2,
        description: 'Full bridge position — hands and feet on ground, hips pushed high. Opens shoulders and spine.',
        progressionPreview: 'Short Bridge',
      },
    ],
    progress: {
      'tmb-forward-roll': { status: 'mastered', currentStep: 2 },
      'tmb-cartwheel': { status: 'completed', currentStep: 2 },
      'tmb-aerial': { status: 'locked', currentStep: 0 },
      'tmb-headstand': { status: 'completed', currentStep: 2 },
      'tmb-bridge': { status: 'in_progress', currentStep: 1 },
    },
  },

  // ── Juggling (pattern-focused, not ball-count) ──
  {
    id: 'juggling',
    name: 'Juggling',
    image: '/images/goals/three-ball-cascade.webp',
    defaultGoalSlug: 'mills-mess',
    categories: [{ id: 'balls', name: 'Balls', color: '#f59e0b' }],
    skills: [
      {
        id: 'jgb-three-ball-cascade',
        name: '3-Ball Cascade',
        abbr: 'Cascade',
        categoryId: 'balls',
        requires: [],
        progressions: 2,
        description: 'The foundational three-ball pattern — continuous alternating arcs. 100 catches to master.',
        progressionPreview: 'Three Ball Flash',
      },
      {
        id: 'jgb-reverse-cascade',
        name: 'Reverse Cascade',
        categoryId: 'balls',
        requires: ['jgb-three-ball-cascade'],
        progressions: 2,
        description: 'Cascade with throws going over the top instead of under. Builds pattern awareness.',
        progressionPreview: 'Single Over-the-Top',
      },
      {
        id: 'jgb-mills-mess',
        name: 'Mills Mess',
        categoryId: 'balls',
        requires: ['jgb-reverse-cascade'],
        progressions: 2,
        description: 'Arms cross and uncross creating a weaving figure-eight. Iconic juggling trick.',
        progressionPreview: 'Mills Mess (one cycle)',
      },
      {
        id: 'jgb-under-the-leg',
        name: 'Under the Leg',
        categoryId: 'balls',
        requires: ['jgb-three-ball-cascade'],
        progressions: 2,
        description: 'Throw one ball under a lifted leg while maintaining the cascade pattern.',
        progressionPreview: 'Single Under-Leg Throw',
      },
      {
        id: 'jgb-behind-the-back',
        name: 'Behind the Back',
        categoryId: 'balls',
        requires: ['jgb-under-the-leg'],
        progressions: 2,
        description: 'Throw a ball behind the back so it arcs over the shoulder to the other hand.',
        progressionPreview: 'Single Behind-Back Throw',
      },
    ],
    progress: {
      'jgb-three-ball-cascade': { status: 'mastered', currentStep: 2 },
      'jgb-reverse-cascade': { status: 'in_progress', currentStep: 1 },
      'jgb-mills-mess': { status: 'locked', currentStep: 0 },
      'jgb-under-the-leg': { status: 'in_progress', currentStep: 1 },
      'jgb-behind-the-back': { status: 'locked', currentStep: 0 },
    },
  },
];

export const LIBRARY_IDS = DEMO_LIBRARIES.map((l) => l.id);
